# NumPy Arrays
<hr>

NumPy arrays are of two types:
 1. <b><u>Vectors</u></b> - Vectors are one-dimensional arrays, as determined by the number of square brackets [], which is only one. It can be of any length.
 2. <b><u>Matrices</u></b>  - Matrices are two-dimensional arrays, in which the length of the arrays should be the same. The dimensions of the Matrix are determined by the length of the array and the number of square brackets [] at the beginning. The length and the number of arrays can be anything of your choice; however keep in mind that the length of the array should be kept the same throughout all the arrays in the matrix.

<hr width = "40%" height = 1px style = "colour: #CCCCCC">

## Simple Implementation 
Now let's learn how to actually code and implement these NumPy arrays.

In [ ]:
import numpy as np

list1 = [0,1,2,3,4,5]
list2 = [6,7,8,9,10,11]
list3 = [12,13,14,15,16,17]

arr1 = np.array(list1) # Vector
arr2 = np.array((list1, list2, list3)) # Matrix

print('These are all the lists.')
print(list1,list2,list3)
print('')
print('The following are Arrays:\n\nVector')
print(arr1)
print('')
print('Matrix')
print(arr2)

These are all the lists.
[0, 1, 2, 3, 4, 5] [6, 7, 8, 9, 10, 11] [12, 13, 14, 15, 16, 17]

The following are Arrays:

Vector
[0 1 2 3 4 5]

Matrix
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


<hr width = "40%" height = 1px style = "colour: #CCCCCC">
<br>
We can validate the difference between a list and an array by running the following cells; we see tat when we make an array the typecast "array" is visible, however in case of a list it simply appears in square brackets [].

In [16]:
list([1,2,3,4,5])

[1, 2, 3, 4, 5]

In [17]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

<hr width = "40%" height = 1px style = "colour: #CCCCCC">

## Special NumPy Array Commands

We can use the following code to create an array consisting of a range of numbers(from start to stop) :

     np.arange(start, stop+1, step)


In [20]:
np.arange(0,100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

We can make other special arrays consisting of all zeros or all ones using the following commands:


     np.zeros(x) 
     # To make a vector of length 'x', consisting of only 0.
     np.ones(x) 
     # To make a vector of length 'x', consisting of only 1.


And if we want to make a matrix of dimensions x * y


     np.zeros((x,y))  
     # To make a matrix of length 'x * y', consisting of only 0.
     np.ones((x,y))  
     # To make a matrix of length 'x * y', consisting of only 1.

In [23]:
x = 5
y = 6

In [24]:
np.zeros(x)

array([0., 0., 0., 0., 0.])

In [25]:
np.ones(x)

array([1., 1., 1., 1., 1.])

In [27]:
np.zeros((x,y))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((x,y))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

To get evenly spaced points between x and y we can use the following command:

     np.linspace(x,y,endpoints)

In [31]:
np.linspace(x,y,100)

array([5.        , 5.01010101, 5.02020202, 5.03030303, 5.04040404,
       5.05050505, 5.06060606, 5.07070707, 5.08080808, 5.09090909,
       5.1010101 , 5.11111111, 5.12121212, 5.13131313, 5.14141414,
       5.15151515, 5.16161616, 5.17171717, 5.18181818, 5.19191919,
       5.2020202 , 5.21212121, 5.22222222, 5.23232323, 5.24242424,
       5.25252525, 5.26262626, 5.27272727, 5.28282828, 5.29292929,
       5.3030303 , 5.31313131, 5.32323232, 5.33333333, 5.34343434,
       5.35353535, 5.36363636, 5.37373737, 5.38383838, 5.39393939,
       5.4040404 , 5.41414141, 5.42424242, 5.43434343, 5.44444444,
       5.45454545, 5.46464646, 5.47474747, 5.48484848, 5.49494949,
       5.50505051, 5.51515152, 5.52525253, 5.53535354, 5.54545455,
       5.55555556, 5.56565657, 5.57575758, 5.58585859, 5.5959596 ,
       5.60606061, 5.61616162, 5.62626263, 5.63636364, 5.64646465,
       5.65656566, 5.66666667, 5.67676768, 5.68686869, 5.6969697 ,
       5.70707071, 5.71717172, 5.72727273, 5.73737374, 5.74747

To make an indentity matrix we use the following command:

     np.eye(x, y, k) # k is a constant which determines if it is an upper(if positive) or lower(if negative) diagonal


In [38]:
np.eye(x,y,1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

<hr width = "40%" height = 1px style = "colour: #CCCCCC">

## Some Common NumPy Random Methods

In [ ]:
np.random.rand(5) # To make a vector consisting of 5 random uniform values from 0 to 1

array([0.37225858, 0.88214324, 0.50499087, 0.93588127, 0.47323555])

In [ ]:
np.random.rand(5,5) # To make a matrix consisting of 25(5*5) random uniform values from 0 to 1

array([[0.94950404, 0.37606783, 0.83645175, 0.64465471, 0.26312382],
       [0.45275567, 0.24805845, 0.36068266, 0.22170711, 0.87836939],
       [0.26034431, 0.62775921, 0.81198195, 0.04863693, 0.69198829],
       [0.38262554, 0.20625932, 0.91012937, 0.89936439, 0.8706372 ],
       [0.68070392, 0.39143533, 0.59448531, 0.85148825, 0.45662149]])

In [ ]:
np.random.randn(5)

array([ 0.76826322,  2.48731157,  1.75750566, -0.14096035,  0.44318506])

In [43]:
np.random.randn(5,5)

array([[ 1.38513967,  0.76828575,  1.08499161, -0.16315531,  2.87889878],
       [-1.23093706,  1.1044809 , -0.92845944,  0.41937249,  0.069168  ],
       [ 1.45824825, -0.1313039 ,  0.49504387, -0.92604105, -0.69587288],
       [ 0.47555769,  1.17833544,  0.14217888,  1.58659246,  0.64448681],
       [ 1.13658944, -1.94170823,  1.76337107,  1.1822648 ,  0.58436478]])

In [44]:
np.random.randint(1,100)

41

In [47]:
np.random.randint(1,100,(x,3,y))

array([[[18, 47, 33, 25, 82, 10],
        [16, 95, 22, 60, 32,  2],
        [80, 64, 92, 73, 22, 97]],

       [[28, 34, 37, 21, 77, 90],
        [32, 62, 72, 59, 30, 48],
        [86, 49, 26, 89, 85, 40]],

       [[38,  7, 36, 44, 70, 33],
        [18, 56, 58, 21,  7, 32],
        [60, 96, 78,  9, 98, 41]],

       [[63, 60, 39, 22, 52, 26],
        [86, 14, 23,  3, 38, 72],
        [80, 72, 29, 28, 98,  7]],

       [[74, 67, 51,  9, 78,  2],
        [18, 74, 59, 84, 86, 47],
        [50, 70, 64, 57, 93, 30]]])

## Reshaping Arrays
Returns an array containing the same data with a new shape.
     
     arr.reshape(len,width)

In [50]:
arr1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

## Shape Attribute

Shape is an attribute that arrays have (not a method):

     arr.shape

In [51]:
arr1.shape

(6,)

In [52]:
arr1.reshape(3,2).shape

(3, 2)

## dtype Attribute

You can also grab the data type of the object in the array using the following code:
     
     arr.dtype

In [53]:
arr1.dtype

dtype('int64')

<hr>